services:
    postgres:
        image: ankane/pgvector
        container_name: loremaster-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: loremaster
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
