services:
    postgres:
        image: ankane/pgvector
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: loremaster
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        command: ["redis-server", "--appendonly", "yes"]

volumes:
    pgdata:
    redis-data:
