export const AiRules = {
    SPLIT_CHUNK_SIZE: 400,
    SPLIT_CHUNK_OVERLAP: 40,
    VECTOR_SEARCH_DISTANCE_THRESHOLD: 0.7,
    VECTOR_SEARCH_BASE_CHUNKS: 3,
    VECTOR_SEARCH_MAX_CHUNKS: 20,
    VECTOR_SEARCH_GROWTH_FACTOR: 1.5,
};
